# Generated by Django 3.0.11 on 2020-12-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banglorejobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Company', models.CharField(max_length=100)),
                ('Tittle', models.CharField(max_length=100)),
                ('Eligibility', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNO', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hydjobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Company', models.CharField(max_length=100)),
                ('Tittle', models.CharField(max_length=100)),
                ('Eligibility', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNO', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Punejobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Company', models.CharField(max_length=100)),
                ('Tittle', models.CharField(max_length=100)),
                ('Eligibility', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNO', models.IntegerField()),
            ],
        ),
    ]
